[package]
name = "game-of-rife"
version = "0.0.2"
authors = ["Armand Adroher <aadroher@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
im = "15.0.0"
